# vim: set filetype=yaml sw=2:
sudo: required
dist: trusty

language: python

# Supported CPython versions:
# https://en.wikipedia.org/wiki/CPython#Version_history
python:
 - "3.6"
 - "3.5"
 - "3.4"
 - "3.3"
 - "3.2"
 - "2.7"
 - "2.6"

install:
 - pip install -U setuptools wheel

script:
 - make build

 # make dist
 - cd build/dist
 - mkdir -p ../tarballs
 - python setup.py -q sdist --dist-dir ../tarballs --formats=bztar,gztar,zip

 # make wheels
 - python setup.py -q bdist_wheel --universal --dist-dir=../tarballs

 # make test
 - cd pytz/tests
 - python test_lazy.py
 - python test_tzinfo.py
 - python test_docs.py
 - cd ../../../..
 - python gen_tests.py
 - python test_zdump.py
